version: "3"
services:
  app:
    container_name: "konomi"
    image: "undermakingbook/konomi"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/work:ro
    environment:
      GRANT_SUDO: "yes"
    command: python
  db:
    container_name: postgres
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - ${POSTGRES_DIR}:/var/lib/postgresql/data