version: "3"
services:
  app:
    container_name: "konomi"
    image: "undermakingbook/konomi"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/work:ro
    environment:
      GRANT_SUDO: "yes"
    command: python